version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./config/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql # Создадим БД для MLFLOW
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      retries: 5
      start_period: 5s
    restart: always

  fastapi_app:
    build: .
    container_name: fastapi_container
    environment:
      - WORKERS=8 # Кол-во workers для Guvicorn
      - DEBUG=False  # Продакшн-режим
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy

  mlflow-service:
    image: ghcr.io/mlflow/mlflow:v2.15.1
    container_name: mlflow-service
    env_file:
      - .env
    environment:
      MLFLOW_S3_ENDPOINT_URL: https://storage.yandexcloud.net
      AWS_ENDPOINT_URL: https://storage.yandexcloud.net
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ru-central1
      MLFLOW_TRACKING_URI: postgresql://postgres:${POSTGRES_PASSWORD}@postgres_db:5432/mlflow_db
    command:
      - bash
      - -c
      - |
        pip install boto3 psycopg2-binary --quiet
        mlflow server --host 0.0.0.0 \
            --backend-store-uri postgresql://postgres:${POSTGRES_PASSWORD}@postgres_db:5432/mlflow_db \
            --default-artifact-root s3://graduate/mlflow --serve-artifacts
    expose:
      - "5000"
    ports:
      - "5050:5000"
    volumes:
      - mlflow-data:/mlflow
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - fastapi_app
      - mlflow-service
      - rabbitmq
      - static-server
    restart: always

  static-server:
    image: nginx:latest
    container_name: static_server
    volumes:
      - ./static:/usr/share/nginx/html # Передает статику с хоста
      - ./config/static-server/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "80"

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    env_file:
      - .env
    ports:
      - "15672:15672"  # Для доступа к Web UI
      - "5672:5672"    # Для подключения RabbitMQ клиентов
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq" 
      - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf  # Монтируем конфиг
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    depends_on:
      - fastapi_app
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres-db-volume:
  mlflow-data:
  nginx-logs:
  rabbitmq_data:
    driver: local