from fastapi import FastAPI
from pydantic import BaseModel
import random

app = FastAPI()

# Модель для входных данных
class TextInput(BaseModel):
    text: str

@app.get("/")
def read_root():
    return {"message": "Probability prediction is the text generated by the model!"}

# Маршрут для обработки POST-запроса
@app.post("/predict")
def predict(text_input: TextInput):
    # Генерируем случайное значение от 0 до 1
    random_value = random.random()
    random_value = round(random_value, 3)
    
    # Возвращаем результат
    return {"text": text_input.text, "Generated prob: ": random_value}

# Запуск сервера (для локального тестирования)
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)